trigger:
  - develop
variables:
  vmImageName: 'ubuntu-latest'
  DockerImageName: 'dev-goart/goart-portal-qa/goart-portal-dev'
stages:
  - stage: DevBuildStage
    displayName: Dev Build Stage
    jobs:
      - job: DevBuildJob
        displayName: Dev Build Job
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
          - script: |
              npm install
            displayName: 'npm install'
          - script: |
              npm run build
            displayName: 'npm build'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact Cloud Run'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
          - task: Docker@2
            displayName: 'Login to Container Registry'
            inputs:
              command: login
              containerRegistry: 'admin-gar-connection-dev'
          - task: Docker@2
            displayName: 'Build and push image'
            inputs:
              Dockerfile: 'Dockerfile'
              command: buildAndPush
              repository: '$(DockerImageName)'
          - task: DeleteFiles@1
            displayName: 'Remove unneeded folders'
            inputs:
              contents: |
                node_modules
          - task: PublishPipelineArtifact@0
            displayName: 'Publish Artifact for Firebase'
            inputs:
              artifactName: 'DevBuildArt'
              targetPath: $(System.DefaultWorkingDirectory)
